title: なまたまご公式サイト
description: ゲームと思想をつむぐ開発者のポートフォリオ
url: "https://egg3d.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Author
author:
  name   : "なまたまご"
  avatar : "/assets/images/avatar.png"
  bio    : "ゲーム開発者｜思想発信中"

# Navigation
header_pages:
  - index.md
  - _pages/about.md

# Markdown対応
markdown: kramdown
